name: Deployment zu TEST EC2 Webserver

on: push

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:

            - name: checkout
              uses: actions/checkout@v5

            - name: ssh setup
              run: | 
                mkdir -p ~/.ssh
                echo "${{secrets.EC2_TEST_WEBSERVER_SSH_KEY}}" > ~/.ssh/SSH_Test_Webserver_KEY
                chmod 400 ~/.ssh/SSH_Test_Webserver_KEY
                ssh-keyscan -H ${{secrets.EC2_TEST_WEBSERVER_IP}}  >> ~/.ssh/known_hosts    

            - name: indexWebserver.html für nginx bereitstellen
              run: |
                scp -i ~/.ssh/SSH_Test_Webserver_KEY frontend/indexWebserver.html ubuntu@${{secrets.EC2_TEST_WEBSERVER_IP}}:/home/ubuntu/indexWebserver.html
                ssh -i ~/.ssh/SSH_Test_Webserver_KEY ubuntu@${{secrets.EC2_TEST_WEBSERVER_IP}} "sudo cp /home/ubuntu/indexWebserver.html /var/www/html/indexWebserver.html"    